version: '3'

services:
    app:
        build: ./
    storage:
        image: nginx
        volumes:
            - storage:/usr/share/nginx/html
    balancer:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
            - storage
        ports:
            - 80:80
            - 443:443
        links:
            - app:app
            - storage:storage

volumes:
    storage: